KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_appian="appian-secret"
    user_springboot="spring-secret";
};