BEGIN;

CREATE TABLE USERS
(
    ID              BIGSERIAL PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL,
    SURNAME         VARCHAR(255) NOT NULL,
    NICKNAME        VARCHAR(255) NOT NULL,
    EMAIL           VARCHAR(255) NOT NULL,
    PASSWORD_HASHED VARCHAR(255) NULL,
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    DELETED_AT      TIMESTAMP NULL
);

CREATE TABLE PROJECTS
(
    ID              BIGSERIAL PRIMARY KEY,
    CODE            VARCHAR(255) NOT NULL,
    NAME            VARCHAR(255) NOT NULL,
    DESCRIPTION     VARCHAR(511) NOT NULL,
    STATUS          VARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    DELETED_AT      TIMESTAMP NULL
);

CREATE TABLE TASKS
(
    ID              BIGSERIAL PRIMARY KEY,
    TITLE           VARCHAR(255) NOT NULL,
    PROJECT_ID      INT          NOT NULL,
    USER_ID         INT          NULL,
    STATUS          VARCHAR(50)  NOT NULL DEFAULT 'PENDING_APPROVAL',
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    DELETED_AT      TIMESTAMP NULL,

    CONSTRAINT FK_TASKS_PROJECT
        FOREIGN KEY (PROJECT_ID)
            REFERENCES PROJECTS (ID)
            ON DELETE CASCADE,

    CONSTRAINT FK_TASKS_USER
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (ID)
            ON DELETE SET NULL
);

CREATE TABLE TAGS
(
    ID              BIGSERIAL PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    DELETED_AT      TIMESTAMP NULL
);

CREATE TABLE TASK_TAGS
(
    TASK_ID         INT NOT NULL,
    TAG_ID          INT NOT NULL,

    PRIMARY KEY (TASK_ID, TAG_ID),

    CONSTRAINT FK_TASK_TAGS_TASK
        FOREIGN KEY (TASK_ID)
            REFERENCES TASKS (ID)
            ON DELETE CASCADE,

    CONSTRAINT FK_TASK_TAGS_TAG
        FOREIGN KEY (TAG_ID)
            REFERENCES TAGS (ID)
            ON DELETE CASCADE
);

END;