BEGIN;

-- Contents
CREATE TABLE USERS
(
    ID              SERIAL PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL,
    SURNAME         VARCHAR(255) NOT NULL,
    NICKNAME        VARCHAR(255) NOT NULL,
    EMAIL           VARCHAR(255) NOT NULL,
    PASSWORD_HASHED VARCHAR(255) NULL,
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    DELETED_AT      TIMESTAMP NULL
);

END;