BEGIN;

CREATE TABLE USERS
(
    ID              SERIAL PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL,
    SURNAME         VARCHAR(255) NOT NULL,
    NICKNAME        VARCHAR(255) NOT NULL,
    EMAIL           VARCHAR(255) NOT NULL,
    PASSWORD_HASHED VARCHAR(255) NULL,
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    DELETED_AT      TIMESTAMP NULL
);

CREATE TABLE PROJECTS
(
    ID              SERIAL PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL,
    DESCRIPTION     VARCHAR(511) NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    DELETED_AT      TIMESTAMP NULL
);

CREATE TABLE TASKS
(
    ID              SERIAL PRIMARY KEY,
    TITLE           VARCHAR(255) NOT NULL,
    PROJECT_ID      INT          NOT NULL,
    USER_ID         INT          NULL,
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    DELETED_AT      TIMESTAMP NULL,

    CONSTRAINT FK_TASKS_PROJECT
        FOREIGN KEY (PROJECT_ID)
            REFERENCES PROJECTS (ID)
            ON DELETE CASCADE,

    CONSTRAINT FK_TASKS_USER
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (ID)
            ON DELETE SET NULL
);

CREATE TABLE TAGS
(
    ID              SERIAL PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE TASK_TAGS
(
    TASK_ID         INT NOT NULL,
    TAG_ID          INT NOT NULL,

    PRIMARY KEY (TASK_ID, TAG_ID),

    CONSTRAINT FK_TASK_TAGS_TASK
        FOREIGN KEY (TASK_ID)
            REFERENCES TASKS (ID)
            ON DELETE CASCADE,

    CONSTRAINT FK_TASK_TAGS_TAG
        FOREIGN KEY (TAG_ID)
            REFERENCES TAGS (ID)
            ON DELETE CASCADE
);

--
CREATE TABLE event_publication
(
    id               UUID NOT NULL PRIMARY KEY,
    listener_id      VARCHAR(512) NOT NULL,
    event_type       VARCHAR(512) NOT NULL,
    serialized_event VARCHAR(4000) NOT NULL,
    publication_date TIMESTAMP WITH TIME ZONE NOT NULL,
    completion_date  TIMESTAMP WITH TIME ZONE,
    completion_attempts INTEGER
);

END;